// Generated by CoffeeScript 1.7.1
(function() {
    var app, gems;

    app = angular.module('app', []);

    app.controller('StoreController', function() {
        this.products = gems;
        return void 0;
    });

    app.controller('TabController', function() {
        this.tab = 0;
        this.selectedProduct = gems[this.tab];
        this.setTab = function(val) {
            this.tab = val;
            return this.selectedProduct = gems[this.tab];
        };
        this.isSet = function(val) {
            return this.tab === val;
        };
        return void 0;
    });

    app.directive('product', function() {
        return {
            restrict: 'E',
            templateUrl: 'product.html',
            scope: {
                product: '='
            }
        };
    });

    gems = [
        {
            index: 0,
            name: 'Azurite',
            price: 2.95,
            produced: Date.now(),
            desc: "fjfghdf ew dsfgdsfgdfgfgfg sdfsdf "
        }, {
            index: 1,
            name: 'Bloodstone',
            price: 5.95,
            produced: Date.now(),
            desc: " asfsdg yfhdsfgdsfgdfgfgfg sdfsdf "
        }, {
            index: 2,
            name: 'Zircon',
            price: 3.95,
            produced: Date.now(),
            desc: " uyub wr dsfgdsfgdfgfgfg sdfsdf "
        }
    ];

}).call(this);
